#!/usr/bin/env python3
"""Generate the Apple backend's shader header the way a macOS host would, on Linux.

**Why this exists.** Cargo compiles build scripts for the *host*, not for the
target, so `#[cfg(target_os = "macos")] mod macos_build` in
`crates/gpui_apple/build.rs` is compiled out on every runner we have. The cbindgen
step that reads five shader sources has therefore never run in any gate, on any
leg — which is how a `build.rs` that read those files from *sibling crates* got
as far as the registry, where every consumer's macOS build failed with
`ParseCannotOpenFile`.

`check_reads.py` catches that statically, from the archive. This catches it
dynamically, the way a macOS host does: it runs the real cbindgen over the
crate's real vendored sources. The two answer different questions, and their
failures read differently — one says *this path is not in your package*, the
other shows cbindgen's own message when it cannot read the sources.

**How.** The crate's `build.rs` is copied with two edits, both asserted, so that a
change in its shape fails loudly rather than silently checking nothing:

* the `#[cfg(target_os = "macos")]` gates are removed, so the macOS module
  compiles and `run()` is called on this host;
* the two shader-compilation calls in `run()` are removed, because `xcrun` and the
  stitched source are the parts a Linux host cannot do, and neither is what this
  check is about.

The crate's `vendor/` and `src/metal_renderer.rs` are copied beside it, because
those are what cbindgen reads. If generation fails, the build script panics
exactly as it did for a consumer.

Usage:
    apple_build_check.py --stage src                  # every candidate crate found
    apple_build_check.py --crate src/crates/gpui_apple
"""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import shutil
import subprocess
import sys

# The attribute that keeps the whole thing from running anywhere but macOS.
HOST_GATE = '#[cfg(target_os = "macos")]'

# The tail of `run()`: the parts that need `xcrun` or a stitched file. Removed as
# one block so no attribute is left dangling over the next statement.
COMPILATION = re.compile(
    r'\n[ \t]*#\[cfg\(feature = "runtime_shaders"\)\][ \t]*\n'
    r'[ \t]*emit_stitched_shaders\(&header_path\);[ \t]*\n'
    r'[ \t]*#\[cfg\(not\(feature = "runtime_shaders"\)\)\][ \t]*\n'
    r'[ \t]*compile_metal_shaders\(&header_path\);[ \t]*\n'
)

# A generated header is tens of kilobytes of type declarations; anything smaller
# means cbindgen emitted an empty file and the check proved nothing.
MINIMUM_HEADER = 1024

MANIFEST = """\
# Generated by apple_build_check.py: a host for the Apple crate's build script.
[package]
name = "{package}"
version = "0.0.0"
edition = "2021"
publish = false

# Standalone: this lives inside the staged checkout, and without this cargo would
# look for it in that workspace's member list.
[workspace]

[build-dependencies]
cbindgen = {{ version = "0.28.0", default-features = false }}
"""


def candidates(stage: pathlib.Path) -> list[pathlib.Path]:
    """Crates whose build script feeds cbindgen.

    One per target normally: `gpui_apple` from 1.17 on, `gpui_macos` before that —
    whichever name the branch uses for the crate that reads the shader sources.
    """
    found = []
    for pattern in ("*/Cargo.toml", "*/*/Cargo.toml", "*/*/*/Cargo.toml"):
        for manifest in sorted((stage / "crates").glob(pattern)):
            crate = manifest.parent
            build_script = crate / "build.rs"
            if not build_script.is_file():
                continue
            if (crate / "vendor" / "gpui_engine").is_dir() or "find_sibling_crate_dir" in (
                build_script.read_text()
            ):
                found.append(crate)
    return found


def transform(crate: pathlib.Path) -> str:
    """The crate's build script, rendered runnable on a host that is not macOS."""
    text = (crate / "build.rs").read_text()

    if HOST_GATE not in text:
        raise SystemExit(
            f"{crate}: build.rs has no {HOST_GATE} gate to strip, so its shape has "
            "changed and this check no longer knows what it is looking at"
        )
    gated = text.count(HOST_GATE)
    text = text.replace(HOST_GATE, "")

    stripped = COMPILATION.sub("", text, count=1)
    if stripped == text:
        raise SystemExit(
            f"{crate}: build.rs no longer calls emit_stitched_shaders and "
            "compile_metal_shaders in the shape this check strips — update the check"
        )
    print(f"    stripped {gated} host gate(s) and the shader-compilation calls")
    return stripped


def check(crate: pathlib.Path, work: pathlib.Path) -> int:
    if not (crate / "build.rs").is_file():
        print(f"FAIL {crate.name}: no build.rs", file=sys.stderr)
        return 1
    renderer = crate / "src" / "metal_renderer.rs"
    if not renderer.is_file():
        print(f"FAIL {crate.name}: no src/metal_renderer.rs for cbindgen to read", file=sys.stderr)
        return 1

    package = "apple-build-check-" + crate.name.replace("_", "-")
    harness = work / package
    if harness.exists():
        shutil.rmtree(harness)
    (harness / "src").mkdir(parents=True)
    (harness / "Cargo.toml").write_text(MANIFEST.format(package=package))
    (harness / "build.rs").write_text(transform(crate))
    (harness / "src" / "main.rs").write_text("fn main() {}\n")
    shutil.copyfile(renderer, harness / "src" / "metal_renderer.rs")
    vendor = crate / "vendor"
    if vendor.is_dir():
        shutil.copytree(vendor, harness / "vendor", dirs_exist_ok=True)
    else:
        # The pre-fix shape: nothing vendored, so the build script reaches for
        # sibling crates that a packaged crate does not have. Let cbindgen say so
        # rather than deciding here.
        print(f"    note: {crate.name} has no vendor/; cbindgen will look beside it")

    print(f"==> {crate.name}: cbindgen over its own vendor/ and metal_renderer.rs")
    target = work / "target"
    result = subprocess.run(
        ["cargo", "build"],
        cwd=harness,
        env={**os.environ, "CARGO_TARGET_DIR": str(target)},
        capture_output=True,
        text=True,
    )
    header = next(target.glob(f"debug/build/{package}-*/out/scene.h"), None)
    if result.returncode != 0 or header is None:
        print(f"FAIL {crate.name}: the shader header was not generated", file=sys.stderr)
        for line in (result.stderr or result.stdout or "").strip().splitlines()[-12:]:
            print(f"        {line}", file=sys.stderr)
        return 1

    size = header.stat().st_size
    if size < MINIMUM_HEADER:
        print(f"FAIL {crate.name}: a {size}-byte header proves nothing", file=sys.stderr)
        return 1
    print(f"--- {crate.name}: {size} bytes of SceneHeader generated")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stage", type=pathlib.Path,
                        help="a staged checkout; every candidate crate in it is checked")
    parser.add_argument("--crate", type=pathlib.Path, action="append", default=[],
                        help="a crate directory to check; repeatable")
    parser.add_argument("--work", type=pathlib.Path,
                        help="where to build the harness; under the stage by default")
    args = parser.parse_args(argv)

    crates = [crate.resolve() for crate in args.crate]
    work = args.work
    if args.stage:
        stage = args.stage.resolve()
        crates += candidates(stage)
        work = work or stage / "target" / "apple-check"
    if not crates:
        raise SystemExit("nothing to check: pass --stage or --crate")

    work = (work or pathlib.Path.cwd() / "apple-check").resolve()
    work.mkdir(parents=True, exist_ok=True)
    failures = sum(check(crate, work) for crate in crates)
    if failures:
        print(f"\n{failures} crate(s) cannot generate their shader header", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
